{{- $context := . -}}    
{{- range .Values.ports }}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: microverse-{{ .name }}-{{ $context.Values.name }}
  labels:
    app: {{ template "microverse.name" $context }}
    chart: {{ template "microverse.name" $context }}-0.0.1
    release: {{ $context.Values.name }}
    heritage: Tiller
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    nginx.org/websocket-services: microverse-{{ .name }}-{{ $context.Values.name }}
spec:
  tls:
    - hosts:
        - {{ .name }}.{{ $context.Values.domain }}
      secretName: microverse-{{ .name }}-tls
  rules:
    - host: {{ .name }}.{{ $context.Values.domain }}
      http:
        paths:
          - path: /{{ $context.Values.name }}
            backend:
              serviceName: microverse-{{ .name }}-{{ $context.Values.name }}
              servicePort: 80

{{- end }}

