apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: microverse-app-{{ .Values.name }}
  labels:
    app: microverse-app-{{ .Values.name }}
    chart: microverse-app-{{ .Values.name }}-0.0.1
    release: {{ .Values.name }}
    heritage: Tiller
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
spec:
  tls:
    - hosts:
        - app.{{ .Values.domain }}
      secretName: microverse-app-tls
  rules:
    - host: app.{{ .Values.domain }}
      http:
        paths:
          - path: /{{ .Values.name }}
            backend:
              serviceName: microverse-app-{{ .Values.name }}
              servicePort: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: microverse-dashboard-{{ .Values.name }}
  labels:
    app: microverse-dashboard-{{ .Values.name }}
    chart: microverse-app-{{ .Values.name }}-0.0.1
    release: {{ .Values.name }}
    heritage: Tiller
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
spec:
  tls:
    - hosts:
        - dashboard.{{ .Values.domain }}
      secretName: microverse-dashboard-tls
  rules:
    - host: dashboard.{{ .Values.domain }}
      http:
        paths:
          - path: /{{ .Values.name }}
            backend:
              serviceName: microverse-dashboard-{{ .Values.name }}
              servicePort: 80
