{{- $context := . -}}    
{{- range .Values.ports }}
---
apiVersion: v1
kind: Service
metadata:
  name: microverse-{{ .name }}-{{ $context.Values.name }}
  labels:
    app: {{ template "microverse.name" $context }}
    chart: {{ template "microverse.name" $context }}-0.0.1
    release: {{ $context.Values.name }}
    heritage: Tiller
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: {{ .port }}
    protocol: TCP
    name: {{ .name }}
  selector:
    app: {{ template "microverse.name" $context }}
    release: {{ $context.Values.name }}
{{- end }}


